# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install

repos:
  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.2
    hooks:
      - id: prettier
        exclude: archetypes|docs|data|layouts|resources|static|themes/*
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/packit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-rebase
        args:
          - git://github.com/packit/packit.dev.git
