baseURL = "https://packit.dev/"
publishDir = "docs"
languageCode = "en-us"
title = "Packit"
theme = "minos"
paginate = 5

[params]
  subtitle = "Upstream project ← → Downstream distribution"
  brand = "Packit"

[menu]
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 1
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "posts"
    url = "/posts/"
  [[menu.main]]
    name = "Source-git"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "source-git"
    url = "/source-git/"
  [[menu.main]]
    name = "Packit-as-a-Service"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 4
    identifier = "packit-as-a-service"
    url = "/packit-as-a-service/"
[social]
  github = "packit-service/packit"
