baseURL = "https://packit.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Packit"
theme = "hugo-theme-learn"
defaultContentLanguageInSubdir = false
paginate = 10
googleAnalytics = "UA-143669536-1"

[outputs]
home = ["HTML", "JSON"]

[params]
  subtitle = "Upstream project ← → Downstream distribution"
  brand = "Packit"
  email = "user-cont-team@redhat.com"
  disableInlineCopyToClipBoard = true
  disableAssetsBusting = true
  themeVariant = "packit"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "gr"
url = "https://github.com/packit/packit"
weight = 10


[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Packit-as-a-Service GitHub app"
identifier = "paas"
url = "https://github.com/apps/packit-as-a-service"
weight = 11


[social]
  github = "packit/packit"
