baseURL = "https://packit.dev/"
publishDir = "docs"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Packit"
theme = "hugo-theme-learn"
defaultContentLanguageInSubdir = false
paginate = 10

[outputs]
home = ["HTML", "JSON"]

[params]
  subtitle = "Upstream project ← → Downstream distribution"
  brand = "Packit"
  email = "user-cont-team@redhat.com"
  disableInlineCopyToClipBoard = true
  themeVariant = "red"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "gr"
url = "https://github.com/packit-service/packit"
weight = 10


[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Packit as a Service on Marketplace"
identifier = "paas"
url = "https://github.com/apps/packit-as-a-service"
weight = 11


[social]
  github = "packit-service/packit"
