baseURL = "https://packit.dev/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Packit"
theme = "book"
defaultContentLanguageInSubdir = false
paginate = 10
googleAnalytics = "UA-143669536-1"

[outputs]
home = ["HTML", "JSON"]

[params]
subtitle = "Upstream project ← → Downstream distribution"
brand = "Packit"
email = "user-cont-team@redhat.com"
BookLogo = 'packit_logo.png'
BookSection = '*'

[menu]
  [[menu.before]]
    name = "Dashboard"
    url = "https://dashboard.packit.dev"
  [[menu.after]]
    name = "Status page"
    url = "https://status.packit.dev"
