name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'packit/packit.dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          CNAME: packit.dev
          GITHUB_ACTOR: jpopelka
          HUGO_VERSION: 0.75.1
          HUGO_EXTENDED: true
          TARGET_REPO: packit/packit.dev-github-pages
          TOKEN: ${{ secrets.TOKEN }}
